version: '3.8'

services:
  db:
    image: postgres:16-alpine
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - sda-network
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  api:
    image: sda-image:backend
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - sda-network
    ports:
      - "8081:8000"
    depends_on:
      - db
      - redis
      - minio
      - neo4j
      # - bot

  redis:
    image: redis:7-alpine
    restart: unless-stopped
    networks:
      - sda-network
    ports:
      - "6379:6379"
    command: redis-server --save 60 1 --loglevel warning

  minio:
    image: minio/minio:latest
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - sda-network
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
    command: server /data --address ':9000' --console-address ':9001'

  neo4j:
    image: neo4j:5-community
    restart: unless-stopped
    networks:
      - sda-network
    environment:
      - NEO4J_AUTH=${NEO4J_USER}/${NEO4J_PASSWORD}
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - neo4j_data:/data

  adminer:
    image: adminer:latest
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - sda-network
    ports:
      - "8080:8080"
    depends_on:
      - db

networks:
  sda-network:
    driver: bridge

volumes:
  pg_data:
  minio_data:
  neo4j_data: